# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization_disgn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(190, 140)
        Form.setMinimumSize(QtCore.QSize(190, 140))
        Form.setMaximumSize(QtCore.QSize(190, 140))
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 171, 119))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_login = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_login.setObjectName("line_login")
        self.verticalLayout.addWidget(self.line_login)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_password = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_password.setObjectName("line_password")
        self.verticalLayout.addWidget(self.line_password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_sign_in = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sign_in.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(239, 124, 101);\n"
"border_radius: 30;")
        self.btn_sign_in.setObjectName("btn_sign_in")
        self.horizontalLayout.addWidget(self.btn_sign_in)
        self.btn_sign_up = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sign_up.setAutoFillBackground(False)
        self.btn_sign_up.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(239, 124, 101)")
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.horizontalLayout.addWidget(self.btn_sign_up)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Authorization"))
        self.label.setText(_translate("Form", " login:"))
        self.label_2.setText(_translate("Form", " password:"))
        self.btn_sign_in.setText(_translate("Form", "Sign in"))
        self.btn_sign_up.setText(_translate("Form", "Sign up"))
